# Generated by Django 5.2.14 on 2026-05-25 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_remove_task_user_task_author_task_executor_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"verbose_name": "Задача", "verbose_name_plural": "Задачи"},
        ),
        migrations.AlterModelTable(
            name="task",
            table="tasks",
        ),
    ]
