# Generated by Django 5.2.14 on 2026-05-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_task_options_alter_task_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Имя"),
        ),
    ]
