# Generated by Django 5.2.14 on 2026-05-28 18:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_task_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["id"], "verbose_name": "Задача", "verbose_name_plural": "Задачи"},
        ),
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Дата создания"),
        ),
    ]
