# Generated by Django 5.2.14 on 2026-05-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0005_alter_label_options_alter_label_created_at_and_more"),
        ("tasks", "0006_alter_task_options_alter_task_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="labels",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", related_query_name="tasks", to="labels.label", verbose_name="Метки"
            ),
        ),
    ]
