sonar.projectKey=vavilin-di_middle-python-project-52
sonar.organization=vavilin-di

sonar.python.coverage.reportPaths=coverage.xml
sonar.sources=task_manager/
sonar.tests=task_manager/applications/*/tests.py,task_manager/applications/*/tests/,task_manager/utilities/tests/
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/tests/**,**/tests.py

sonar.python.version=3.14
sonar.sourceEncoding=UTF-8