# Generated by Django 5.2.14 on 2026-05-25 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0002_alter_label_created_at_alter_label_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="label",
            options={"verbose_name": "Метка", "verbose_name_plural": "Метки"},
        ),
        migrations.AlterModelTable(
            name="label",
            table="labels",
        ),
    ]
