# Generated by Django 5.2.14 on 2026-05-28 18:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0003_alter_label_options_alter_label_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="label",
            options={"ordering": ["id"], "verbose_name": "Метка", "verbose_name_plural": "Метки"},
        ),
        migrations.AlterField(
            model_name="label",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Дата создания"),
        ),
    ]
