# Generated by Django 5.2.14 on 2026-05-30 21:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0004_alter_label_options_alter_label_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="label",
            options={
                "ordering": ["id"],
                "verbose_name": "LabelVerboseName",
                "verbose_name_plural": "LabelVerboseNamePlural",
            },
        ),
        migrations.AlterField(
            model_name="label",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="LabelCreatedAt"),
        ),
        migrations.AlterField(
            model_name="label",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False, verbose_name="LabelID"),
        ),
        migrations.AlterField(
            model_name="label",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="LabelName"),
        ),
    ]
