# Generated by Django 5.2.14 on 2026-05-25 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="status",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="status",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Имя"),
        ),
    ]
