# Generated by Django 5.2.14 on 2026-05-25 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0002_alter_status_created_at_alter_status_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="status",
            options={"verbose_name": "Статус", "verbose_name_plural": "Статусы"},
        ),
        migrations.AlterModelTable(
            name="status",
            table="statuses",
        ),
    ]
