# Generated by Django 5.2.14 on 2026-05-28 18:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0003_alter_status_options_alter_status_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="status",
            options={"ordering": ["id"], "verbose_name": "Статус", "verbose_name_plural": "Статусы"},
        ),
        migrations.AlterField(
            model_name="status",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Дата создания"),
        ),
    ]
