# Generated by Django 5.2.14 on 2026-05-30 21:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0004_alter_status_options_alter_status_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="status",
            options={
                "ordering": ["id"],
                "verbose_name": "StatusVerboseName",
                "verbose_name_plural": "StatusVerboseNamePlural",
            },
        ),
        migrations.AlterField(
            model_name="status",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="StatusCreatedAt"),
        ),
        migrations.AlterField(
            model_name="status",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False, verbose_name="StatusID"),
        ),
        migrations.AlterField(
            model_name="status",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="StatusName"),
        ),
    ]
