name: unit-testing

on:
  workflow_call:
    secrets:
      SECRET_KEY_FOR_TESTS:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Run tests with coverage
        run: uv run coverage run --source=task_manager -m pytest -n 0
        env:
          USE_SQLITE_FOR_TESTS: 1
          SECRET_KEY: ${{ secrets.SECRET_KEY_FOR_TESTS }}

      - name: Generate coverage XML report
        run: uv run coverage xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml